# Use postgresDB
version: "3.1"

services:
    chat-db:
        image: postgres
        container_name: dbchat
        environment:
            POSTGRES_PASSWORD: "senha123"
            POSTGRES_USER: "victor"
            POSTGRES_DB: "chat"
        ports:
            - "5432:5432"
    cache:
        image: redis
        ports:
            - "6379:6379"

    

