# Use postgresDB
version: "3.1"

services:
    chat-db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: "${password_pg}"
        ports:
            - "5555:5432"
    cache:
        image: redis:6.2-alpine
        ports:
            - '6378:6379'
        command: redis-server --save 20 1 --loglevel warning --requirepass ${password_redis}
